service: Aviation Dataset Processing - Cleaning

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  memorySize: 1500
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"

functions:
  handle_zipfile:
    handler: src/clean_data.handle_zipfile
  get_zipfiles:
    handler: src/get_zipfiles.handler
